; Waveshare ESP32-S3-Touch-LCD-7
; Estacion Meteorologica con LVGL

[env:waveshare_esp32s3_touch_lcd_7]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ESP32-S3 con PSRAM OPI (8MB)
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Velocidad de subida
upload_speed = 460800
upload_protocol = esptool
upload_flags =
    --before=default_reset
    --after=hard_reset
    --chip=esp32s3
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    ; USB-CDC para monitor serie por USB
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; LVGL: buscar lv_conf.h en /src
    -DLV_CONF_INCLUDE_SIMPLE
    -I src

lib_deps =
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^6.21.5
    ayushsharma82/ElegantOTA@^3.1.0
